name: JayTAKDupePlugin
version: '${project.version}'
main: io.jaytak.jaytakdupeplugin.JayTAKDupePlugin
api-version: '1.20'

commands:
  jaytakdupe:
    description: Dupes item in hand.
    aliases:
      - jdupe
      - dupe
      - jd
    usage: /dupe  /jdupe  /jd     optional args + - / * x X [operand]
    permission: jaytakdupeplugin.dupe